In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Insurance_Charges.csv')

In [5]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [9]:
datasets

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [11]:
indep=datasets[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=datasets[['charges']]

In [13]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [109]:
from sklearn.svm import NuSVR
regressor=NuSVR(kernel="linear",C=1.0)
regressor=regressor.fit(X_train,y_train)

C:\Users\arunn\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [111]:
y_pred=regressor.predict(X_test)

In [113]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [115]:
r_score

0.09537262617850806

In [117]:
regressor.intercept_

array([2272.5156666])

In [119]:
regressor.n_support_

array([447])

In [121]:
regressor.support_

array([  1,   7,   9,  13,  14,  16,  17,  24,  25,  26,  28,  29,  31,
        32,  36,  42,  43,  45,  50,  52,  53,  54,  55,  56,  58,  61,
        64,  69,  74,  78,  79,  80,  81,  83,  86,  94,  95,  97, 100,
       102, 105, 107, 109, 113, 114, 116, 119, 126, 128, 129, 131, 132,
       133, 134, 135, 138, 143, 145, 147, 148, 149, 152, 155, 157, 158,
       162, 163, 164, 166, 168, 169, 170, 171, 174, 176, 182, 184, 189,
       192, 193, 194, 195, 198, 199, 201, 203, 204, 212, 214, 215, 216,
       218, 219, 224, 229, 230, 234, 237, 240, 241, 245, 248, 249, 250,
       251, 252, 254, 257, 259, 261, 262, 263, 265, 266, 268, 271, 274,
       279, 280, 281, 282, 288, 290, 291, 293, 295, 299, 302, 304, 307,
       309, 312, 313, 315, 316, 317, 319, 322, 323, 324, 325, 326, 329,
       330, 331, 332, 333, 335, 338, 342, 344, 345, 347, 348, 349, 352,
       353, 355, 356, 359, 360, 362, 365, 367, 368, 370, 375, 377, 380,
       383, 387, 388, 390, 392, 393, 396, 397, 398, 399, 401, 40

In [123]:
regressor.support_vectors_

array([[50.   ,  1.   , 32.3  ,  1.   ,  1.   ],
       [45.   ,  0.   , 35.815,  0.   ,  0.   ],
       [31.   ,  0.   , 26.62 ,  0.   ,  0.   ],
       ...,
       [42.   ,  1.   , 35.97 ,  2.   ,  0.   ],
       [40.   ,  1.   , 25.08 ,  0.   ,  0.   ],
       [33.   ,  0.   , 18.5  ,  1.   ,  0.   ]])

In [125]:
regressor.coef_

array([[256.99420956, -21.05839148,  -2.85924846, 132.68097402,
        172.        ]])

In [129]:
age_input=float(input("age:"))
sex_input=float(input("sex_male"))
bmi_input=float(input("BMI "))
child_input=int(input("# of Children:"))
smoker_input=int(input("Smoker:"))

age: 27
sex_male 1
BMI  19
# of Children: 1
Smoker: 1


In [131]:
result=regressor.predict([[age_input,sex_input,bmi_input,child_input,smoker_input]])

C:\Users\arunn\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but NuSVR was fitted with feature names
  warnings.warn(


In [133]:
result

array([9440.65618655])