In [336]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [338]:
# Reading the Dataset
dataset = pd.read_csv('Insurance_Charges.csv')

In [340]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [342]:
datasets=pd.get_dummies(dataset,drop_first=True)

In [344]:
datasets

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [346]:
indep=datasets[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=datasets[['charges']]

In [348]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [350]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(criterion="squared_error",n_estimators=100, random_state=42 )
regressor=regressor.fit(X_train,y_train)

C:\Users\arunn\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


In [352]:
y_pred=regressor.predict(X_test)

In [354]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [356]:
r_score

0.860730739714308

In [358]:
regressor.feature_importances_

array([0.14854791, 0.00809511, 0.23447745, 0.02298878, 0.58589075])

In [360]:
import pickle
filename="finalized_model_InsuranceCharge.sav"

In [362]:
pickle.dump(regressor,open(filename,'wb'))

In [364]:
loaded_model=pickle.load(open("finalized_model_InsuranceCharge.sav",'rb'))

In [372]:
result=loaded_model.predict([[29,1,19,1,1]])

C:\Users\arunn\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [374]:
result

array([15373.4800748])

In [368]:
age_input=float(input("age:"))
sex_input=float(input("sex_male"))
bmi_input=float(input("BMI "))
child_input=int(input("# of Children:"))
smoker_input=int(input("Smoker:"))

age: 20
sex_male 1
BMI  19
# of Children: 1
Smoker: 1


In [ ]:
result=loaded_model.predict([[age_input,sex_input,bmi_input,child_input,smoker_input]])

In [370]:
result

array([15373.4800748])